version: '3.7'

services:
  socket-api:
    build:
      context: .
      target: development
    volumes:
      - /usr/src/app/dist
      - /usr/src/app/node_modules
      - .:/usr/src/app
    ports:
      - 80:3000
      - 9229:9229
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - socket-network
networks:
  socket-network:

